name = "floating-island"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-02-24"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "dy.ci", zone_name = "dy.ci", custom_domain = true },
]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "FAILOVER_CHAT_KV"
id = "0796f7634adf4e94a60237175d2ff86e"
preview_id = "04eaf97936754f6e835a6eb7363d981a"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[placement]
region = "aws:ap-east-1"
